### PR TITLE
BAP-330 - Replace variables when looking up repositories in a deployment target.

### PR DESCRIPTION
**Pull request by breser**

### CODE REVIEW

**Comment by breser** [comment]
Fixes the bug here:
https://www.jfrog.com/jira/browse/BAP-330

**Comment by eyalbe4** [comment]
@breser - thanks a lot for identifying this issue!
I'd I like to make a small change to fix you suggested and do the "substituteVariables" on the username and the password after the if statement, to support also variables substitution if the the variables are configured in the global Artifactory server configuration:
```console
        if (StringUtils.isNotBlank(username) && StringUtils.isNotBlank(password)) {
            password = TaskUtils.decryptIfNeeded(password);
        } else {
            username = serverConfig.getUsername();
            password = serverConfig.getPassword();
        }
        username = substituteVariables(username);
        password = substituteVariables(password);
```
What do you think?

**Comment by split3** [comment]
@eyalbe4 and @breser I think that change makes sense.

**Comment by breser** [comment]
Ahh yes.  Good call.

**Comment by split3** [comment]
Did this change actually get made or is somebody waiting on somebody else?

**Comment by denebeim** [comment]
I believe @breser was supposed to revise his pull request to include the suggestions @eyalbe4 made.

**Comment by eyalbe4** [comment]
This fix was added and releases as part of version 1.9.2 of the plugin [BAP-330](https://www.jfrog.com/jira/browse/BAP-330) tracks this change.

**Comment by breser** [comment]
Closing this.  They didn't merge this PR.  But they did commit an equivalent.

**Pull request closed without merging**
